package com.ale.sisenoroscuro.classes;

public enum  ActionType {
    GET_CARD, START, MIRADA, PLEAD,
    PLEAD_ACCEPTED, PLEAD_NOT_ACCEPTED, PLAY_EXCUSE, PLAY_INTERRUMPIR,
    PLAY_PASAR, GET_PLEAD_CARD, GAME_OVER, GAME_NOT_OVER
}
